### Variables
@baseUrl = http://127.0.0.1:5000
@token = Bearer tu_token_jwt_aquí

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nombre_usuario": "admin",
  "password": "password123"
}